#!/usr/bin/python

import sys
import subprocess
import re

p = subprocess.Popen(["whois", sys.argv[1]], stdout=subprocess.PIPE)
output, err = p.communicate()
output = output.splitlines(True)

whoisfields = {}

for line in output:
	match = re.search(r':', line)
	if match:
		k, v = line.split(':', 1)
		whoisfields[k.lower()] = v.strip()

# reverse dict of the one in https://gist.github.com/rogerallen/1583606

country_codes = {
'AN':     'Andorra',
'AE':     'United Arab Emirates',
'AF':     'Afghanistan',
'AC':     'Antigua and Barbuda',
'AV':     'Anguilla',
'AL':     'Albania',
'AM':     'Armenia',
'AO':     'Angola',
'AY':     'Antarctica',
'AR':     'Argentina',
'AQ':     'American Samoa',
'AU':     'Austria',
'AS':     'Australia',
'AA':     'Aruba',
'AJ':     'Azerbaijan',
'BK':     'Bosnia and Herzegovina',
'BB':     'Barbados',
'BG':     'Bangladesh',
'BE':     'Belgium',
'UV':     'Burkina Faso',
'BU':     'Bulgaria',
'BA':     'Bahrain',
'BY':     'Burundi',
'BN':     'Benin',
'TB':     'Saint Barthalemy',
'BD':     'Bermuda',
'BX':     'Brunei',
'BL':     'Bolivia',
'BR':     'Brazil',
'BF':     'Bahamas',
'BT':     'Bhutan',
'BV':     'Bouvet Island',
'BC':     'Botswana',
'BO':     'Belarus',
'BH':     'Belize',
'CA':     'Canada',
'CK':     'Cocos Islands',
'CG':     'Democratic Republic of the Congo',
'CT':     'Central African Republic',
'CF':     'Republic of the Congo',
'SZ':     'Switzerland',
'IV':     'Ivory Coast',
'CW':     'Cook Islands',
'CI':     'Chile',
'CM':     'Cameroon',
'CH':     'China',
'CO':     'Colombia',
'CS':     'Costa Rica',
'CU':     'Cuba',
'CV':     'Cape Verde',
'UC':     'Curacao',
'KT':     'Christmas Island',
'CY':     'Cyprus',
'EZ':     'Czech Republic',
'GM':     'Germany',
'DJ':     'Djibouti',
'DA':     'Denmark',
'DO':     'Dominica',
'DR':     'Dominican Republic',
'AG':     'Algeria',
'EC':     'Ecuador',
'EN':     'Estonia',
'EG':     'Egypt',
'WI':     'Western Sahara',
'ER':     'Eritrea',
'SP':     'Spain',
'ET':     'Ethiopia',
'FI':     'Finland',
'FJ':     'Fiji',
'FK':     'Falkland Islands',
'FM':     'Micronesia',
'FO':     'Faroe Islands',
'FR':     'France',
'GB':     'Gabon',
'UK':     'United Kingdom',
'GJ':     'Grenada',
'GG':     'Georgia',
'FG':     'French Guiana',
'GK':     'Guernsey',
'GH':     'Ghana',
'GI':     'Gibraltar',
'GL':     'Greenland',
'GA':     'Gambia',
'GV':     'Guinea',
'GP':     'Guadeloupe',
'EK':     'Equatorial Guinea',
'GR':     'Greece',
'SX':     'South Georgia and the South Sandwich Islands',
'GT':     'Guatemala',
'GQ':     'Guam',
'PU':     'Guinea-Bissau',
'GY':     'Guyana',
'HK':     'Hong Kong',
'HM':     'Heard Island and McDonald Islands',
'HO':     'Honduras',
'HR':     'Croatia',
'HA':     'Haiti',
'HU':     'Hungary',
'ID':     'Indonesia',
'EI':     'Ireland',
'IS':     'Israel',
'IM':     'Isle of Man',
'IN':     'India',
'IO':     'British Indian Ocean Territory',
'IZ':     'Iraq',
'IR':     'Iran',
'IC':     'Iceland',
'IT':     'Italy',
'JE':     'Jersey',
'JM':     'Jamaica',
'JO':     'Jordan',
'JA':     'Japan',
'KE':     'Kenya',
'KG':     'Kyrgyzstan',
'CB':     'Cambodia',
'KR':     'Kiribati',
'CN':     'Comoros',
'SC':     'Saint Kitts and Nevis',
'KN':     'North Korea',
'KS':     'South Korea',
'KV':     'Kosovo',
'KU':     'Kuwait',
'CJ':     'Cayman Islands',
'KZ':     'Kazakhstan',
'LA':     'Laos',
'LE':     'Lebanon',
'ST':     'Saint Lucia',
'LS':     'Liechtenstein',
'CE':     'Sri Lanka',
'LI':     'Liberia',
'LT':     'Lesotho',
'LH':     'Lithuania',
'LU':     'Luxembourg',
'LG':     'Latvia',
'LY':     'Libya',
'MO':     'Morocco',
'MN':     'Monaco',
'MD':     'Moldova',
'MJ':     'Montenegro',
'RN':     'Saint Martin',
'MA':     'Madagascar',
'RM':     'Marshall Islands',
'MK':     'Macedonia',
'ML':     'Mali',
'BM':     'Myanmar',
'MG':     'Mongolia',
'MC':     'Macao',
'CQ':     'Northern Mariana Islands',
'MB':     'Martinique',
'MR':     'Mauritania',
'MH':     'Montserrat',
'MT':     'Malta',
'MP':     'Mauritius',
'MV':     'Maldives',
'MI':     'Malawi',
'MX':     'Mexico',
'MY':     'Malaysia',
'MZ':     'Mozambique',
'WA':     'Namibia',
'NC':     'New Caledonia',
'NG':     'Niger',
'NF':     'Norfolk Island',
'NI':     'Nigeria',
'NU':     'Nicaragua',
'NL':     'Netherlands',
'NO':     'Norway',
'NP':     'Nepal',
'NR':     'Nauru',
'NE':     'Niue',
'NZ':     'New Zealand',
'MU':     'Oman',
'PM':     'Panama',
'PE':     'Peru',
'FP':     'French Polynesia',
'PP':     'Papua New Guinea',
'RP':     'Philippines',
'PK':     'Pakistan',
'PL':     'Poland',
'SB':     'Saint Pierre and Miquelon',
'PC':     'Pitcairn',
'RQ':     'Puerto Rico',
'WE':     'Palestinian Territory',
'PO':     'Portugal',
'PS':     'Palau',
'PA':     'Paraguay',
'QA':     'Qatar',
'RE':     'Reunion',
'RO':     'Romania',
'RI':     'Serbia',
'RS':     'Russia',
'RW':     'Rwanda',
'SA':     'Saudi Arabia',
'BP':     'Solomon Islands',
'SE':     'Seychelles',
'SU':     'Sudan',
'OD':     'South Sudan',
'SW':     'Sweden',
'SN':     'Singapore',
'SH':     'Saint Helena',
'SI':     'Slovenia',
'SV':     'Svalbard and Jan Mayen',
'LO':     'Slovakia',
'SL':     'Sierra Leone',
'SM':     'San Marino',
'SG':     'Senegal',
'SO':     'Somalia',
'NS':     'Suriname',
'TP':     'Sao Tome and Principe',
'ES':     'El Salvador',
'NN':     'Sint Maarten',
'SY':     'Syria',
'WZ':     'Swaziland',
'TK':     'Turks and Caicos Islands',
'CD':     'Chad',
'FS':     'French Southern Territories',
'TO':     'Togo',
'TH':     'Thailand',
'TI':     'Tajikistan',
'TL':     'Tokelau',
'TT':     'East Timor',
'TX':     'Turkmenistan',
'TS':     'Tunisia',
'TN':     'Tonga',
'TU':     'Turkey',
'TD':     'Trinidad and Tobago',
'TV':     'Tuvalu',
'TW':     'Taiwan',
'TZ':     'Tanzania',
'UP':     'Ukraine',
'UG':     'Uganda',
'US':     'United States',
'UY':     'Uruguay',
'UZ':     'Uzbekistan',
'VT':     'Vatican',
'VC':     'Saint Vincent and the Grenadines',
'VE':     'Venezuela',
'VI':     'British Virgin Islands',
'VQ':     'U.S. Virgin Islands',
'VM':     'Vietnam',
'NH':     'Vanuatu',
'WF':     'Wallis and Futuna',
'WS':     'Samoa',
'YM':     'Yemen',
'MF':     'Mayotte',
'SF':     'South Africa',
'ZA':     'Zambia',
'ZI':     'Zimbabwe',
'YI':     'Serbia and Montenegro',
'NT':     'Netherlands Antilles',
}

print "Country code is " + whoisfields["country"]
print "Country is " + country_codes[whoisfields["country"]]